Installer (#1)
* Add gitignore

* WIP: MSYS2 installer

* Tweaks

* .appveyor.yml: add artifacts

* .appveyor.yml: add quotes around commands

* .appveyor.yml: try to mitigate against MSYS signature problem

error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to update mingw64 (invalid or corrupted database (PGP signature))

* .appveyor.yml: try to update to VS2019 image to get more recent MSYS

See https://help.appveyor.com/discussions/problems/28154-please-update-msys2

* .appveyor.yml: try to kill all MSYS processes before rebase

* MSYS: install rsync

* Add missing dependency msys-expat-1.dll

Got a generic error when ansible was trying to import pyexpat.
strace'ing python showed that python was able to pick up
pyexpat.cpython-38-x86_64-msys.dll from /usr/lib/python3.8/lib-dynload,
however the DLL failed to load.

Using dumpbin to find the dependencies revealed this:

dumpbin /dependents pyexpat.cpython-38-x86_64-msys.dll
Microsoft (R) COFF/PE Dumper Version 14.28.29335.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file pyexpat.cpython-38-x86_64-msys.dll

File Type: DLL

  Image has the following dependencies:

    msys-python3.8.dll
    msys-expat-1.dll
    msys-2.0.dll
    KERNEL32.dll

  Summary

        1000 .bss
        1000 .buildid
        2000 .data
        1000 .edata
        2000 .idata
        1000 .pdata
        2000 .rdata
        1000 .reloc
        7000 .text
        1000 .xdata

* Add another missing dependency: msys-ffi-7.dll

* Tweaks

* Turn off verbose output for rsync

* AppVeyor: try to fix quote escaping for pywinrm install

* AppVeyor: try to fix quote escaping for pywinrm install

* AppVeyor: try to fix quote escaping for pywinrm install

* Fixes to release.sh

* More tweaks

* Change from bat script to ps script (run as admin)

* Try to setup WinRM

* Remove 'Press any key to continue' prompt from run.sh, since we have it in run.ps1